addons:
  apt:
    packages:
	- libharfbuzz-dev
	- libfribidi-dev
	- libfreetype6-dev
	- libpng-dev
	- libtiff5-dev
	- libjpeg-dev

before_install:
  - Rscript -e "install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dependencies=TRUE)"
  - Rscript -e "devtools::document()"

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
